# Generated by Django 6.0.4 on 2026-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categoriabrowser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='URL base de la API (sin barra final)')),
                ('domain', models.CharField(help_text='Dominio del proveedor', max_length=100)),
                ('embed_url', models.URLField(help_text='URL base para embeds (sin barra final)')),
                ('url_pattern', models.TextField(help_text='Regex para identificar URLs del proveedor')),
                ('api_search_endpoint', models.CharField(default='/api/v2/video/search/', max_length=100)),
                ('api_video_endpoint', models.CharField(default='/api/v2/video/id/', max_length=100)),
                ('api_params', models.JSONField(default=dict, help_text='Parámetros extra para la API (ej: thumbsize, format)')),
                ('api_extra_flags', models.JSONField(default=dict, help_text='Flags adicionales de la API (ej: gay, lq)')),
            ],
            options={
                'verbose_name': 'configuración del proveedor',
                'verbose_name_plural': 'configuraciones del proveedor',
            },
        ),
    ]
