# Generated by Django 6.0.4 on 2026-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_marcador_eliminado_marcador_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcador',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
