# Generated by Django 6.0.4 on 2026-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_marcador_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='URL base de la API (sin barra final)')),
                ('cdn_url', models.URLField(help_text='URL del CDN de miniaturas')),
                ('file_url', models.URLField(help_text='URL del CDN de archivos originales')),
                ('url_pattern', models.TextField(help_text='Regex para identificar URLs del proveedor')),
            ],
            options={
                'verbose_name': 'configuración de galería',
                'verbose_name_plural': 'configuraciones de galería',
            },
        ),
    ]
