# Generated by Django 6.0.4 on 2026-09-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_img_provider_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
