# Generated by Django 6.0.4 on 2026-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_marcador_url_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marcador',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
