# Generated by Django 6.0.4 on 2026-09-17 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_orden_to_integerfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='URL base de la API (sin barra final)')),
            ],
            options={
                'verbose_name': 'configuración de archivos',
                'verbose_name_plural': 'configuraciones de archivos',
            },
        ),
        migrations.CreateModel(
            name='CarpetaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('nivel', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='gestion.carpetaarchivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_archivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'unique_together': {('usuario', 'nombre', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('url_archivo', models.CharField(max_length=500)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(default='image', help_text='image, video, other', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_base64', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.carpetaarchivo')),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
